[tox]
envlist = py3{9,10,11,12,13},lint,coverage

[testenv]
runner = uv-venv-runner
deps =
    pytest
    pytest-cov
commands =
    pytest {posargs}

[testenv:lint]
deps =
    ruff
commands =
    ruff check upnpclient

[testenv:coverage]
package = editable
deps =
    pytest
    pytest-cov
commands =
    pytest --cov upnpclient --cov-fail-under 80 --cov-report term-missing --durations 5 -v
